### ISSUE TITLE
Error in API server logs

### ISSUE THREAD

**Issue by mattldawson** [NCAR/music-box-interactive#399]
Investigate this error:
```
FileExistsError: [Errno 17] File exists: '/config-archives/e30:1sJaWM:2ZK95erRbCKuVkBbpuMezh1zmc_4JbQ4pTLbFWPbIJA'
api-server                                | ERROR:django.request:Internal Server Error: /api/compress-config
api-server                                | Traceback (most recent call last):
api-server                                |   File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
api-server                                |     response = get_response(request)
api-server                                |   File "/usr/local/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
api-server                                |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
api-server                                |   File "/usr/local/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
api-server                                |     return view_func(*args, **kwargs)
api-server                                |   File "/usr/local/lib/python3.9/site-packages/django/views/generic/base.py", line 104, in view
api-server                                |     return self.dispatch(request, *args, **kwargs)
api-server                                |   File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
api-server                                |     response = self.handle_exception(exc)
api-server                                |   File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
api-server                                |     self.raise_uncaught_exception(exc)
api-server                                |   File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
api-server                                |     raise exc
api-server                                |   File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
api-server                                |     response = handler(request, *args, **kwargs)
api-server                                |   File "/music-box-interactive/interactive/api/api.py", line 129, in post
api-server                                |     zipfile = controller.handle_compress_configuration(
api-server                                |   File "/music-box-interactive/interactive/api/controller.py", line 95, in handle_compress_configuration
api-server                                |     compress_configuration(session_id)
api-server                                |   File "/music-box-interactive/interactive/shared/configuration_utils.py", line 229, in compress_configuration
api-server                                |     zip_file_path = get_zip_file_path(session_id)
api-server                                |   File "/music-box-interactive/interactive/shared/configuration_utils.py", line 57, in get_zip_file_path
api-server                                |     return os.path.join(get_zip_folder_path(session_id), "config.zip")
api-server                                |   File "/music-box-interactive/interactive/shared/configuration_utils.py", line 43, in get_zip_folder_path
api-server                                |     os.makedirs(path, exist_ok=True)
api-server                                |   File "/usr/lib64/python3.9/os.py", line 225, in makedirs
api-server                                |     mkdir(name, mode)
api-server                                | FileExistsError: [Errno 17] File exists: '/config-archives/e30:1sJaWM:2ZK95erRbCKuVkBbpuMezh1zmc_4JbQ4pTLbFWPbIJA'
api-server                                | 127.0.0.1 - - [18/Jun/2024 15:15:51] "POST /api/compress-config HTTP/1.1" 500 -
```

It may be associated with inconsistent failures of the solver, and could be that when this error is triggered, the configuration being uploaded is not successfully loaded and a previous configuration is actually what is run.

I was able to reproduce this error by selecting any example, selecting `Download` in the left navbar, and then rapidly clicking `Download Configuration File` while monitoring the server logs.

**Acceptance Criteria**
- Rapidly clicking `Download Configuration File` leads to multiple downloads of the file, rather than an error.

**Ideas**
- Use a newly generated UUID for the temporary folder while creating the archive, instead of the session ID

**Comment by K20shores** [comment]
no longer applies in the new music box interactive, soon to be released
